# Generated by Django 2.2.13 on 2026-05-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='swabalamban/carousel')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Carousel image',
                'verbose_name_plural': 'Carousel images',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.TextField(max_length=1000, verbose_name='Tagline (Bold)')),
                ('description', models.TextField(max_length=3000)),
                ('picture', models.ImageField(blank=True, upload_to='swabalamban/index')),
                ('banner_image', models.ImageField(blank=True, upload_to='swabalamban/banner')),
                ('caption_en', models.CharField(blank=True, default='', max_length=500)),
                ('caption_or', models.CharField(blank=True, default='', max_length=500)),
                ('order_note', models.TextField(blank=True, default='', help_text='Text above the animated caption (e.g. WhatsApp ordering note).', max_length=1000)),
                ('whatsapp_number', models.CharField(blank=True, default='', help_text='Displayed in the order note, e.g. +91 98765 43210', max_length=30)),
                ('products_heading', models.CharField(blank=True, default='Quality produce from our Swabalamban initiative.', max_length=300)),
            ],
            options={
                'verbose_name': 'Swabalamban Home Page',
                'verbose_name_plural': 'Swabalamban Home Page',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(help_text='Used for modal IDs, e.g. moong → productModalMoong', unique=True)),
                ('label', models.CharField(help_text='Short label on the product card', max_length=120)),
                ('image', models.ImageField(upload_to='swabalamban/products')),
                ('card_theme', models.CharField(choices=[('moong', 'Moong (yellow)'), ('green', 'Green moong'), ('black', 'Black dal'), ('red', 'Red lentils')], default='moong', max_length=10)),
                ('intro', models.TextField(help_text='Opening paragraph in the product modal', max_length=2000)),
                ('nutritional_highlights', models.TextField(help_text='One bullet per line', max_length=2000)),
                ('quality_promise', models.TextField(max_length=1000)),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
