# Generated by Django 2.2.13 on 2026-05-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swabalamban', '0006_title_case_product_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quality_promise',
            field=models.TextField(help_text='One promise per line (shown separated by ·). Bullets (•) on one line also work.', max_length=1000),
        ),
    ]
