# Generated by Django 2.2.13 on 2026-06-28 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swabalamban', '0007_auto_20260528_2300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarouselImage',
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
