# Generated by Django 2.2.13 on 2026-09-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swabalamban', '0008_remove_legacy_pillar_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quality_promise',
            field=models.TextField(help_text='One promise per line (shown as a list on the product modal).', max_length=1000),
        ),
    ]
