# Generated by Django 2.2.13 on 2020-11-15 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bandhuapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('date', models.DateField()),
                ('thumb', models.ImageField(default='charity_work/thumbnails/activity.jpg', upload_to='charity_work/thumbnails')),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('purpose', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=60)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='charity_work/charities/')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Other Activity',
                'verbose_name_plural': 'Other Activities',
                'unique_together': {('title', 'purpose', 'location')},
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.TextField(max_length=1000, verbose_name='Tagline (Bold)')),
                ('description', models.TextField(max_length=3000)),
                ('picture', models.ImageField(upload_to='charity_work/index')),
                ('banner_image', models.ImageField(upload_to='charity_work/banner')),
            ],
            options={
                'verbose_name': 'Other Activities Home Page',
                'verbose_name_plural': 'Other Activities Home Page',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=13, verbose_name='Contact Number')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charitywork.Charity')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bandhuapp.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='charity_work/%Y')),
                ('approved', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='charitywork.Activity')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charitywork.Charity')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='charity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charitywork.Charity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='volunteers',
            field=models.ManyToManyField(to='charitywork.Volunteer'),
        ),
    ]
