# Generated by Django 2.2.13 on 2026-06-28 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charitywork', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='banner_image',
        ),
    ]
