# Generated by Django 2.2.13 on 2026-06-05 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patriotism', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ashram',
            name='reports',
            field=models.TextField(blank=True, help_text='Optional rich text for reports (links, notes).', max_length=5000),
        ),
        migrations.CreateModel(
            name='AshramReportLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(help_text='Google Drive, PDF host, or any URL.', max_length=500)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('ashram', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='report_links', to='patriotism.Ashram')),
            ],
            options={
                'verbose_name': 'Report link',
                'verbose_name_plural': 'Report links',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AshramReportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='patriotism/reports/%Y')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ashram', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='report_files', to='patriotism.Ashram')),
            ],
            options={
                'verbose_name': 'Report file',
                'verbose_name_plural': 'Report files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AshramInvitationLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='PDF or image invitation letter.', upload_to='patriotism/invitation_letters/')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('ashram', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_letter', to='patriotism.Ashram')),
            ],
            options={
                'verbose_name': 'Invitation letter',
                'verbose_name_plural': 'Invitation letters',
            },
        ),
    ]
