# Generated by Django 2.2.13 on 2026-06-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patriotism', '0007_homepage_hero_captions'),
    ]

    operations = [
        migrations.AddField(
            model_name='ashram',
            name='image_caption_en',
            field=models.CharField(blank=True, default='', help_text='Short quote below the hero image.', max_length=500, verbose_name='Image caption (English)'),
        ),
        migrations.AddField(
            model_name='ashram',
            name='image_caption_or',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Image caption (Odia)'),
        ),
        migrations.AlterField(
            model_name='ashram',
            name='image',
            field=models.ImageField(help_text='Large image beside the text. Leave empty to use the first gallery photo.', upload_to='patriotism/thumbnails/', verbose_name='Hero image'),
        ),
    ]
