# Generated by Django 2.2.13 on 2026-06-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevavrata', '0008_entry_hero_captions'),
    ]

    operations = [
        migrations.AddField(
            model_name='ashram',
            name='end_date',
            field=models.DateField(blank=True, help_text='When this Sevavrata activity ends.', null=True, verbose_name='End date'),
        ),
        migrations.AddField(
            model_name='ashram',
            name='start_date',
            field=models.DateField(blank=True, help_text='When this Sevavrata activity begins (shown in the schedule box on the detail page).', null=True, verbose_name='Start date'),
        ),
    ]
