# Generated by Django 2.2.13 on 2020-11-15 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bandhuapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='publications/banner')),
            ],
            options={
                'verbose_name': 'Publications Home Page',
                'verbose_name_plural': 'Publications Home Page',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('thumb', models.ImageField(upload_to='publications/thumb')),
                ('is_visible', models.BooleanField(default=True)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('media', models.FileField(upload_to='publications')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bandhuapp.Profile')),
            ],
        ),
    ]
