# Generated by Django 2.2.13 on 2026-06-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='description',
            field=models.TextField(blank=True, default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='homepage',
            name='picture',
            field=models.ImageField(blank=True, upload_to='publications/index'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tagline',
            field=models.TextField(blank=True, default='', help_text='Shown on the homepage initiative card and this page.', max_length=500, verbose_name='Tagline (bold)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_image',
            field=models.ImageField(blank=True, upload_to='publications/banner'),
        ),
    ]
