# Generated by Django 2.2.13 on 2026-06-28 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_initiatives_per_app_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='banner_image',
        ),
    ]
