# Generated by Django 2.2 on 2020-04-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth',
            field=models.BooleanField(default=False),
        ),
    ]
