# Generated by Django 2.2.13 on 2026-05-14 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ankurayan', '0010_alter_ankurayan_visitors_verbose_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='guest',
            name='sort_order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Lower numbers appear first in guest lists.'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='ankurayan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='ankurayan.Ankurayan'),
        ),
        migrations.CreateModel(
            name='GuestNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='ankurayan.Guest')),
            ],
            options={
                'verbose_name': 'Guest note',
                'verbose_name_plural': 'Guest notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
