# Generated by Django 2.2.13 on 2020-11-15 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.TextField(max_length=1000, verbose_name='About Us Tagline (Bold)')),
                ('desc', models.TextField(max_length=3000, verbose_name='About Us Description')),
            ],
            options={
                'verbose_name_plural': 'About Us Section',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=50, verbose_name='Contact Number')),
                ('email', models.CharField(max_length=50)),
                ('facebook_link', models.CharField(max_length=150)),
                ('twitter_link', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Contact Us Section',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Gallery Section',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='bandhuapp/banner')),
                ('visitors_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Bandhu Home Page',
                'verbose_name_plural': 'Bandhu Home Page',
            },
        ),
        migrations.CreateModel(
            name='Initiatives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ankurayan_desc', models.TextField(max_length=500, verbose_name='Anurayan Tagline')),
                ('ankurayan_thumb', models.ImageField(upload_to='main_page/initiatives', verbose_name='Ankurayan Thumbnail')),
                ('kendra_desc', models.TextField(max_length=500, verbose_name='Anandakendra Tagline')),
                ('kendra_thumb', models.ImageField(upload_to='main_page/initiatives', verbose_name='Anandakendra Thumbnail')),
                ('bandhughar_desc', models.TextField(max_length=500, verbose_name='Bandhughar Tagline')),
                ('bandhughar_thumb', models.ImageField(upload_to='main_page/initiatives', verbose_name='Bandhughar Thumbnail')),
                ('otheract_desc', models.TextField(max_length=500, verbose_name='Other Activities Tagline')),
                ('otheract_thumb', models.ImageField(upload_to='main_page/initiatives', verbose_name='Other Activities Thumbnail')),
                ('publications_desc', models.TextField(max_length=500, verbose_name='Our Publications Tagline')),
                ('publications_thumb', models.ImageField(upload_to='main_page/initiatives', verbose_name='Our Publications Thumbnail')),
            ],
            options={
                'verbose_name_plural': 'Initiatives Section',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanskar_tagline', models.TextField(max_length=500, verbose_name='Sanskar Tagline (Bold)')),
                ('sanskar_desc', models.TextField(max_length=3000, verbose_name='Sanskar Description')),
                ('swaraj_tagline', models.TextField(max_length=500, verbose_name='Swaraj Tagline (Bold)')),
                ('swaraj_desc', models.TextField(max_length=3000, verbose_name='Swaraj Description')),
                ('swabalamban_tagline', models.TextField(max_length=500, verbose_name='Swabalamban Tagline (Bold)')),
                ('swabalamban_desc', models.TextField(max_length=3000, verbose_name='Swabalamban Description')),
            ],
            options={
                'verbose_name_plural': 'Our Mission Section',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='bandhuapp/gallery')),
                ('caption', models.TextField(blank=True, max_length=500, null=True)),
                ('tags', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Gallery Photo',
                'verbose_name_plural': 'Gallery Photos',
            },
        ),
        migrations.CreateModel(
            name='RecentActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date/ Start Date (Optional)')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date (Optional)')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link (not required if inserting file)')),
                ('notice_file', models.FileField(blank=True, null=True, upload_to='notice_files', verbose_name='Notice File (Optional)')),
            ],
            options={
                'verbose_name_plural': 'Recent Activities',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('tagline', models.TextField(max_length=1500)),
            ],
            options={
                'verbose_name_plural': 'Volunteer Section',
            },
        ),
        migrations.CreateModel(
            name='SwarajCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='bandhuapp/swaraj')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandhuapp.Mission')),
            ],
            options={
                'verbose_name': 'Swaraj Photo',
                'verbose_name_plural': 'Swaraj Photos',
            },
        ),
        migrations.CreateModel(
            name='SwabalambanCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='bandhuapp/swabalamban')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandhuapp.Mission')),
            ],
            options={
                'verbose_name': 'Swabalamban Photo',
                'verbose_name_plural': 'Swabalamban Photos',
            },
        ),
        migrations.CreateModel(
            name='SanskarCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='bandhuapp/sanskar')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandhuapp.Mission')),
            ],
            options={
                'verbose_name': 'Sanskar Photo',
                'verbose_name_plural': 'Sanskar Photos',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('contact_no', models.CharField(max_length=13, verbose_name='Contact Number')),
                ('street_address1', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('street_address2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=25)),
                ('pincode', models.CharField(max_length=10)),
                ('profession', models.CharField(max_length=500)),
                ('profile_pic', models.ImageField(default='profile_photos/man.png', upload_to='profile_photos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
