# Generated by Django 2.2 on 2020-06-07 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('contact_no', models.CharField(max_length=13, verbose_name='Contact Number')),
                ('street_address1', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('street_address2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=25)),
                ('pincode', models.CharField(max_length=10)),
                ('profession', models.CharField(max_length=500)),
                ('profile_pic', models.ImageField(default='profile_photos/man.png', upload_to='profile_photos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
