# Generated by Django 2.2 on 2020-05-18 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandhuapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='display_picture',
            new_name='profile_pic',
        ),
    ]
