# Generated by Django 2.2 on 2020-05-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandhuapp', '0002_auto_20200519_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile_photos/man.png', upload_to=''),
        ),
    ]
