# Generated by Django 2.2.13 on 2022-10-18 20:02

import bandhuapp.helpers
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandhuapp', '0002_auto_20201115_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlData',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(max_length=255, validators=[django.core.validators.URLValidator()])),
                ('hash', models.CharField(default=bandhuapp.helpers._createHash, max_length=255, primary_key=True, serialize=False)),
                ('times_followed', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
