# Generated by Django 2.2 on 2020-05-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandhuapp', '0004_auto_20200525_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ankurayan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='2020', max_length=4)),
                ('theme', models.CharField(max_length=2500)),
                ('logo', models.ImageField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charity_name', models.CharField(max_length=350)),
                ('charity_description', models.TextField(max_length=1000)),
                ('charity_type', models.CharField(max_length=100)),
                ('charity_addressLine1', models.CharField(max_length=350)),
                ('charity_city', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(default='2009-12-31', verbose_name='Date of Birth'),
        ),
    ]
