# Generated by Django 2.2 on 2020-06-05 04:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bandhuapp', '0005_auto_20200526_1322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ankurayan',
        ),
        migrations.DeleteModel(
            name='Charity',
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile_photos/man.png', upload_to='profile_photos'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(max_length=25),
        ),
    ]
