# Generated by Django 2.2.13 on 2023-08-08 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandhuapp', '0005_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('webpage', models.URLField(blank=True)),
                ('about', models.TextField(max_length=1000)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='bandhuapp.Profile')),
            ],
        ),
    ]
