# Generated by Django 2.2.13 on 2023-08-08 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandhuapp', '0006_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeoplesDesignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('desc', models.TextField(max_length=1000)),
                ('rank', models.IntegerField(default=9999)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandhuapp.Designation')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='desg', to='bandhuapp.Staff')),
            ],
        ),
    ]
