# Generated by Django 2.2 on 2020-06-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandhuapp', '0006_auto_20200605_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_no',
            field=models.CharField(max_length=13, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='street_address1',
            field=models.CharField(max_length=255, verbose_name='Address Line 1'),
        ),
    ]
