# Generated by Django 2.2.13 on 2023-08-08 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandhuapp', '0007_peoplesdesignation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('degree', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=255)),
                ('since', models.DateField()),
                ('until', models.DateField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='bandhuapp.Staff')),
            ],
        ),
    ]
