# Generated by Django 2.2.13 on 2023-12-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandhuapp', '0009_staffcontacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('script', models.TextField(max_length=1000)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
