# Generated by Django 2.2.13 on 2024-02-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandhuapp', '0010_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='youtube',
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name='StaffContacts',
        ),
    ]
