# Generated by Django 2.2.13 on 2026-05-15 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandhuapp', '0013_staff_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peoplesdesignation',
            options={'ordering': ['designation__rank', 'rank'], 'verbose_name': 'people designation', 'verbose_name_plural': 'people designations'},
        ),
        migrations.AlterField(
            model_name='peoplesdesignation',
            name='desc',
            field=models.TextField(blank=True, help_text='Optional occupation or short note shown under the role.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='peoplesdesignation',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='bandhuapp.Staff'),
        ),
        migrations.AlterUniqueTogether(
            name='peoplesdesignation',
            unique_together={('staff', 'designation')},
        ),
        migrations.CreateModel(
            name='DesignationRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('rank', models.IntegerField(default=9999)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='bandhuapp.Designation')),
            ],
            options={
                'verbose_name': 'designation role',
                'verbose_name_plural': 'designation roles',
                'ordering': ['rank', 'title'],
                'unique_together': {('designation', 'title')},
            },
        ),
        migrations.AddField(
            model_name='peoplesdesignation',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Office bearer position (only for designations that define roles).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='bandhuapp.DesignationRole'),
        ),
    ]
