# Generated by Django 2.2.13 on 2026-05-18 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandhuapp', '0018_staff_qualifications_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffexperiencephoto',
            name='experience',
        ),
        migrations.DeleteModel(
            name='StaffExperience',
        ),
        migrations.DeleteModel(
            name='StaffExperiencePhoto',
        ),
    ]
