# Generated by Django 2.2.13 on 2026-06-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandhuapp', '0021_annualreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Lower numbers appear first (0 = first slide).')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(max_length=600)),
                ('image', models.ImageField(blank=True, help_text='Optional. Recommended size: wide landscape (4:3).', upload_to='bandhuapp/hero')),
            ],
            options={
                'verbose_name': 'Homepage hero slide',
                'verbose_name_plural': 'Homepage hero slides',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
