# Generated by Django 2.2.13 on 2026-06-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandhuapp', '0022_heroslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Lower numbers appear first (0 = first slide).')),
                ('image', models.ImageField(blank=True, help_text='Photo shown in the About Us carousel.', upload_to='bandhuapp/about')),
                ('caption', models.TextField(blank=True, help_text='Short caption below the photo.', max_length=500)),
            ],
            options={
                'verbose_name': 'About Us slide',
                'verbose_name_plural': 'About Us slides',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About Us section (text)', 'verbose_name_plural': 'About Us section (text)'},
        ),
    ]
