# Generated by Django 2.2.13 on 2026-06-28 10:03

from django.db import migrations, models
import django.db.models.deletion


def _pick_hero_name(photos, prefer_collage=False):
    for row in photos:
        picture = getattr(row, 'picture', None)
        name = (getattr(picture, 'name', None) or '').lower()
        if picture and prefer_collage and 'collage' in name:
            return picture
    for row in photos:
        picture = getattr(row, 'picture', None)
        if picture and getattr(picture, 'name', None):
            return picture
    return None


def migrate_pillar_home_pages(apps, schema_editor):
    Mission = apps.get_model('bandhuapp', 'Mission')
    mission = Mission.objects.first()
    if not mission:
        return

    SanskarHomePage = apps.get_model('bandhuapp', 'SanskarHomePage')
    SanskarHomePhoto = apps.get_model('bandhuapp', 'SanskarHomePhoto')
    SanskarCarousel = apps.get_model('bandhuapp', 'SanskarCarousel')

    if not SanskarHomePage.objects.exists():
        sanskar_photos = list(SanskarCarousel.objects.filter(mission=mission).order_by('id'))
        sanskar_page = SanskarHomePage.objects.create(
            tagline=mission.sanskar_tagline or '',
            description=mission.sanskar_desc or '',
            hero_image=_pick_hero_name(sanskar_photos, prefer_collage=True) or '',
            image_caption_en='"Learning with values lights every life and builds a brighter tomorrow."',
            image_caption_or='"ମୂଲ୍ୟ ସହିତ ଶିକ୍ଷା ପ୍ରତ୍ୟେକ ଜୀବନକୁ ଆଲୋକିତ କରେ ଏବଂ ଏକ ଉଜ୍ଜ୍ୱଳ ଭବିଷ୍ୟତ ଗଢେ।"',
        )
        for index, row in enumerate(sanskar_photos):
            if row.picture:
                SanskarHomePhoto.objects.create(
                    page=sanskar_page,
                    picture=row.picture,
                    sort_order=index,
                )

    SwarajHomePage = apps.get_model('bandhuapp', 'SwarajHomePage')
    SwarajHomePhoto = apps.get_model('bandhuapp', 'SwarajHomePhoto')
    SwarajCarousel = apps.get_model('bandhuapp', 'SwarajCarousel')

    if not SwarajHomePage.objects.exists():
        swaraj_photos = list(SwarajCarousel.objects.filter(mission=mission).order_by('id'))
        swaraj_page = SwarajHomePage.objects.create(
            tagline=mission.swaraj_tagline or '',
            description=mission.swaraj_desc or '',
            hero_image=_pick_hero_name(swaraj_photos) or '',
            text_caption_en='"Empowered communities shape their own future with dignity and voice."',
            text_caption_or='"ସଶକ୍ତ ସମୁଦାୟ ଗରିମା ଏବଂ ନିଜ ଅଧିକାର ସହ ନିଜ ଭବିଷ୍ୟତ ଗଢେ।"',
        )
        for index, row in enumerate(swaraj_photos):
            if row.picture:
                SwarajHomePhoto.objects.create(
                    page=swaraj_page,
                    picture=row.picture,
                    sort_order=index,
                )

    SwabalambanHomePage = apps.get_model('bandhuapp', 'SwabalambanHomePage')
    SwabalambanHomePhoto = apps.get_model('bandhuapp', 'SwabalambanHomePhoto')
    SwabalambanCarousel = apps.get_model('bandhuapp', 'SwabalambanCarousel')

    if not SwabalambanHomePage.objects.exists():
        sw_photos = list(SwabalambanCarousel.objects.filter(mission=mission).order_by('id'))
        legacy_page = None
        legacy_carousel = []
        try:
            legacy_page = apps.get_model('swabalamban', 'HomePage').objects.first()
            legacy_carousel = list(
                apps.get_model('swabalamban', 'CarouselImage').objects.all().order_by('sort_order', 'id')
            )
        except LookupError:
            pass

        hero = _pick_hero_name(sw_photos)
        if not hero and legacy_page and getattr(legacy_page, 'picture', None):
            hero = legacy_page.picture
        if not hero and legacy_carousel:
            hero = _pick_hero_name(legacy_carousel)

        sw_page = SwabalambanHomePage.objects.create(
            tagline=(legacy_page.tagline if legacy_page else '') or mission.swabalamban_tagline or '',
            description=(legacy_page.description if legacy_page else '') or mission.swabalamban_desc or '',
            hero_image=hero or '',
            image_caption_en=(legacy_page.caption_en if legacy_page else '')
            or '"Self-reliance blossoms when villages shape their own path."',
            image_caption_or=(legacy_page.caption_or if legacy_page else '')
            or '"ଗାଁ ନିଜ ପଥ ନିଜେ ଗଢିଲେ ସ୍ୱାବଳମ୍ବନ ଫୁଲିଉଠେ।"',
            order_note=(legacy_page.order_note if legacy_page else '') or '',
            whatsapp_number=(legacy_page.whatsapp_number if legacy_page else '') or '',
            products_heading=(
                (legacy_page.products_heading if legacy_page else '')
                or 'Quality produce from our Swabalamban initiative.'
            ),
        )

        sort_index = 0
        seen = set()
        for row in list(legacy_carousel) + sw_photos:
            picture = getattr(row, 'picture', None)
            name = getattr(picture, 'name', None) or ''
            if not name or name in seen:
                continue
            seen.add(name)
            SwabalambanHomePhoto.objects.create(
                page=sw_page,
                picture=picture,
                sort_order=sort_index,
            )
            sort_index += 1


class Migration(migrations.Migration):

    dependencies = [
        ('bandhuapp', '0023_aboutslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanskarHomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.TextField(blank=True, default='', help_text='Shown on the pillar page and on the homepage mission card.', max_length=500, verbose_name='Tagline (bold)')),
                ('description', models.TextField(blank=True, default='', help_text='Body text for the pillar page. HTML is allowed.', max_length=8000, verbose_name='Main content')),
                ('hero_image', models.ImageField(blank=True, help_text='Large image beside the text. Leave empty to use the first gallery photo.', upload_to='bandhuapp/pillar_heroes')),
                ('image_caption_en', models.CharField(blank=True, default='', help_text='Short quote below the hero image.', max_length=500, verbose_name='Image caption (English)')),
                ('image_caption_or', models.CharField(blank=True, default='', max_length=500, verbose_name='Image caption (Odia)')),
                ('text_caption_en', models.CharField(blank=True, default='', help_text='Optional footer caption inside the text card (used on Swaraj).', max_length=500, verbose_name='Text card caption (English)')),
                ('text_caption_or', models.CharField(blank=True, default='', max_length=500, verbose_name='Text card caption (Odia)')),
            ],
            options={
                'verbose_name': 'Sanskar home page',
                'verbose_name_plural': 'Sanskar home page',
            },
        ),
        migrations.CreateModel(
            name='SwabalambanHomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.TextField(blank=True, default='', help_text='Shown on the pillar page and on the homepage mission card.', max_length=500, verbose_name='Tagline (bold)')),
                ('description', models.TextField(blank=True, default='', help_text='Body text for the pillar page. HTML is allowed.', max_length=8000, verbose_name='Main content')),
                ('hero_image', models.ImageField(blank=True, help_text='Large image beside the text. Leave empty to use the first gallery photo.', upload_to='bandhuapp/pillar_heroes')),
                ('image_caption_en', models.CharField(blank=True, default='', help_text='Short quote below the hero image.', max_length=500, verbose_name='Image caption (English)')),
                ('image_caption_or', models.CharField(blank=True, default='', max_length=500, verbose_name='Image caption (Odia)')),
                ('text_caption_en', models.CharField(blank=True, default='', help_text='Optional footer caption inside the text card (used on Swaraj).', max_length=500, verbose_name='Text card caption (English)')),
                ('text_caption_or', models.CharField(blank=True, default='', max_length=500, verbose_name='Text card caption (Odia)')),
                ('order_note', models.TextField(blank=True, default='', help_text='Ordering note shown above the products section.', max_length=1000)),
                ('whatsapp_number', models.CharField(blank=True, default='', help_text='Shown in the order note if order note is empty.', max_length=30)),
                ('products_heading', models.CharField(blank=True, default='Quality produce from our Swabalamban initiative.', max_length=300)),
            ],
            options={
                'verbose_name': 'Swabalamban home page',
                'verbose_name_plural': 'Swabalamban home page',
            },
        ),
        migrations.CreateModel(
            name='SwarajHomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.TextField(blank=True, default='', help_text='Shown on the pillar page and on the homepage mission card.', max_length=500, verbose_name='Tagline (bold)')),
                ('description', models.TextField(blank=True, default='', help_text='Body text for the pillar page. HTML is allowed.', max_length=8000, verbose_name='Main content')),
                ('hero_image', models.ImageField(blank=True, help_text='Large image beside the text. Leave empty to use the first gallery photo.', upload_to='bandhuapp/pillar_heroes')),
                ('image_caption_en', models.CharField(blank=True, default='', help_text='Short quote below the hero image.', max_length=500, verbose_name='Image caption (English)')),
                ('image_caption_or', models.CharField(blank=True, default='', max_length=500, verbose_name='Image caption (Odia)')),
                ('text_caption_en', models.CharField(blank=True, default='', help_text='Optional footer caption inside the text card (used on Swaraj).', max_length=500, verbose_name='Text card caption (English)')),
                ('text_caption_or', models.CharField(blank=True, default='', max_length=500, verbose_name='Text card caption (Odia)')),
            ],
            options={
                'verbose_name': 'Swaraj home page',
                'verbose_name_plural': 'Swaraj home page',
            },
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'verbose_name_plural': 'Our Mission Section (legacy)'},
        ),
        migrations.CreateModel(
            name='SwarajHomePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='bandhuapp/swaraj')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='bandhuapp.SwarajHomePage')),
            ],
            options={
                'verbose_name': 'Gallery photo',
                'verbose_name_plural': 'Gallery photos',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SwabalambanHomePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='bandhuapp/swabalamban')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='bandhuapp.SwabalambanHomePage')),
            ],
            options={
                'verbose_name': 'Gallery photo',
                'verbose_name_plural': 'Gallery photos',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SanskarHomePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='bandhuapp/sanskar')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='bandhuapp.SanskarHomePage')),
            ],
            options={
                'verbose_name': 'Gallery photo',
                'verbose_name_plural': 'Gallery photos',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.RunPython(migrate_pillar_home_pages, migrations.RunPython.noop),
    ]
