# Generated by Django 2.2.13 on 2026-06-28 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandhuapp', '0024_pillar_home_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanskarcarousel',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='swabalambancarousel',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='swarajcarousel',
            name='mission',
        ),
        migrations.DeleteModel(
            name='Mission',
        ),
        migrations.DeleteModel(
            name='SanskarCarousel',
        ),
        migrations.DeleteModel(
            name='SwabalambanCarousel',
        ),
        migrations.DeleteModel(
            name='SwarajCarousel',
        ),
    ]
