# Generated by Django 2.2.13 on 2026-06-28 10:24

from django.db import migrations


def migrate_initiatives_to_home_pages(apps, schema_editor):
    Initiatives = apps.get_model('bandhuapp', 'Initiatives')
    legacy = Initiatives.objects.first()
    if not legacy:
        return

    targets = (
        ('ankurayan', 'HomePage', 'ankurayan_desc', 'ankurayan_thumb'),
        ('anandakendra', 'HomePage', 'kendra_desc', 'kendra_thumb'),
        ('ashram', 'HomePage', 'bandhughar_desc', 'bandhughar_thumb'),
        ('charitywork', 'HomePage', 'otheract_desc', 'otheract_thumb'),
        ('publications', 'HomePage', 'publications_desc', 'publications_thumb'),
    )

    for app_label, model_name, desc_attr, thumb_attr in targets:
        HomePage = apps.get_model(app_label, model_name)
        page = HomePage.objects.first()
        desc = getattr(legacy, desc_attr, '') or ''
        thumb = getattr(legacy, thumb_attr, None)
        thumb_name = getattr(thumb, 'name', None) or ''

        if page is None:
            create_kwargs = {'tagline': desc}
            if thumb_name:
                create_kwargs['picture'] = thumb
            HomePage.objects.create(**create_kwargs)
            continue

        changed = False
        if desc and not (getattr(page, 'tagline', None) or '').strip():
            page.tagline = desc
            changed = True
        page_picture = getattr(page, 'picture', None)
        if thumb_name and (not page_picture or not getattr(page_picture, 'name', None)):
            page.picture = thumb
            changed = True
        if changed:
            page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bandhuapp', '0025_remove_legacy_pillar_models'),
        ('publications', '0002_initiatives_per_app_homepage'),
    ]

    operations = [
        migrations.RunPython(migrate_initiatives_to_home_pages, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='Initiatives',
        ),
    ]
