# Generated by Django 2.2.13 on 2026-09-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandhuapp', '0027_seed_initiative_home_captions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanskarhomepage',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero image beside the quote on this pillar page and on the homepage mission card. This is separate from gallery photos — deleting gallery items does not remove this image.', upload_to='bandhuapp/pillar_heroes'),
        ),
        migrations.AlterField(
            model_name='swabalambanhomepage',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero image beside the quote on this pillar page and on the homepage mission card. This is separate from gallery photos — deleting gallery items does not remove this image.', upload_to='bandhuapp/pillar_heroes'),
        ),
        migrations.AlterField(
            model_name='swarajhomepage',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero image beside the quote on this pillar page and on the homepage mission card. This is separate from gallery photos — deleting gallery items does not remove this image.', upload_to='bandhuapp/pillar_heroes'),
        ),
    ]
