# Generated by Django 2.2.13 on 2026-06-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prasantaraktadan', '0002_auto_20260605_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeGalleryPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='prasantaraktadan/home_gallery/')),
                ('approved', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
