"""UX review fixes (2026-09-18), Track A: `{% responsive_img %}` tag, the
extended `warm_landing_thumbnails` command, the sitemap, and the cleaned-up
templates (no `src=""`, exactly one `<h1>`).
"""
from django.template import Context, Template
from django.test import Client, TestCase

from bandhuapp.models import Photo
from bandhuapp.tests.support import TempMediaMixin, image_upload


class ResponsiveImgTagTests(TempMediaMixin, TestCase):
    def test_returns_srcset_for_real_image(self):
        photo = Photo.objects.create(picture=image_upload('responsive_tag.gif'), approved=True)
        template = Template('{% load responsive_images %}{% responsive_img photo.picture as img %}{{ img.src }}|{{ img.srcset }}')
        rendered = template.render(Context({'photo': photo}))
        src, srcset = rendered.split('|')
        self.assertTrue(src.endswith('.webp'))
        self.assertIn('480w', srcset)
        self.assertIn('960w', srcset)
        self.assertIn('1600w', srcset)

    def test_falls_back_to_none_for_missing_file(self):
        photo = Photo.objects.create(picture=image_upload('missing_tag.gif'), approved=True)
        photo.picture.storage.delete(photo.picture.name)
        template = Template(
            "{% load responsive_images %}"
            "{% responsive_img photo.picture as img %}"
            "{% if img %}HAS_RESPONSIVE{% else %}{{ photo.picture.url }}{% endif %}"
        )
        rendered = template.render(Context({'photo': photo}))
        # Caller-side fallback pattern used across templates: when the tag
        # returns None, the original field's plain .url is used, unchanged.
        self.assertEqual(rendered, photo.picture.url)

    def test_returns_none_for_empty_field(self):
        template = Template('{% load responsive_images %}{% responsive_img photo.picture as img %}{{ img }}')
        rendered = template.render(Context({'photo': Photo(picture='')}))
        self.assertEqual(rendered, 'None')


class WarmLandingThumbnailsCommandTests(TempMediaMixin, TestCase):
    def test_warms_a_non_landing_field(self):
        from applications.ashram.models import Ashram
        from django.core.management import call_command
        from io import StringIO

        Ashram.objects.create(
            name='Test Bandhughar', locality='Cuttack', description='d', address='a',
            image=image_upload('ashram_warm.gif'), slug='test-bandhughar-warm',
        )
        out = StringIO()
        call_command('warm_landing_thumbnails', stdout=out)
        self.assertIn('Warmed', out.getvalue())
        # The alias thumbnail generated by responsive_image() for this entry's
        # hero image now exists in storage without a request ever asking for it.
        from bandhuapp.helpers import responsive_image
        ashram = Ashram.objects.get(slug='test-bandhughar-warm')
        self.assertIsNotNone(responsive_image(ashram.image))

    def test_warms_a_per_app_homepage_picture(self):
        from applications.ashram.models import HomePage
        from django.core.management import call_command
        from io import StringIO

        home = HomePage.objects.create(
            tagline='t', description='d', picture=image_upload('ashram_home_warm.gif'),
        )
        out = StringIO()
        call_command('warm_landing_thumbnails', stdout=out)
        self.assertIn('Warmed', out.getvalue())
        # content.picture in templates/initiative_program/list_about_section.html
        # (ashram's own HomePage model, not bandhuapp.models.HomePage).
        from bandhuapp.helpers import responsive_image
        home.refresh_from_db()
        self.assertIsNotNone(responsive_image(home.picture))


class SitemapTests(TestCase):
    def test_sitemap_returns_200_and_lists_people(self):
        response = Client().get('/sitemap.xml', SERVER_NAME='localhost')
        self.assertEqual(response.status_code, 200)
        body = response.content.decode()
        self.assertIn('/people/', body)
        self.assertIn('<urlset', body)


class NoEmptySrcAndSingleH1Tests(TestCase):
    """One of the audit's concrete findings: `<img src="">` on first paint,
    and inner pages missing (or duplicating) their `<h1>`."""

    def _assert_clean(self, response):
        self.assertEqual(response.status_code, 200)
        html = response.content.decode()
        self.assertNotIn('src=""', html)
        self.assertEqual(html.count('<h1'), 1)

    def test_people_page(self):
        self._assert_clean(Client().get('/people/'))

    def test_ankurayan_index(self):
        self._assert_clean(Client().get('/ankurayan/'))

    def test_swaraj_pillar_page(self):
        self._assert_clean(Client().get('/swaraj/'))

    def test_swabalamban_pillar_page(self):
        self._assert_clean(Client().get('/swabalamban/'))

    def test_publications_index(self):
        self._assert_clean(Client().get('/publications/'))
