# Generated by Django 2.2.13 on 2020-11-15 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bandhuapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('activity_time', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='AnandaKendra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('address', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='anandakendra/kendras')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Anandakendra',
                'verbose_name_plural': 'Anandakendras',
                'unique_together': {('name', 'locality')},
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.TextField(max_length=1000, verbose_name='Tagline (Bold)')),
                ('description', models.TextField(max_length=3000)),
                ('picture', models.ImageField(upload_to='anandakendra/index')),
                ('banner_image', models.ImageField(upload_to='anandakendra/banner')),
            ],
            options={
                'verbose_name': 'Anandakendra Home Page',
                'verbose_name_plural': 'Anandakendra Home Page',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('guardian_name', models.CharField(max_length=50)),
                ('school_class', models.CharField(max_length=15)),
                ('contact_no', models.CharField(max_length=13, verbose_name='Contact Number')),
                ('address', models.CharField(max_length=250)),
                ('kendra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anandakendra.AnandaKendra')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='anandakendra/activities')),
                ('approved', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anandakendra.Activity')),
                ('kendra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anandakendra.AnandaKendra')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('thumb', models.ImageField(upload_to='anandakendra/events')),
                ('date', models.DateField()),
                ('kendra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anandakendra.AnandaKendra')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('kendra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anandakendra.AnandaKendra')),
            ],
            options={
                'verbose_name_plural': 'Activity Categories',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anandakendra.ActivityCategory'),
        ),
        migrations.CreateModel(
            name='Acharya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acharya_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandhuapp.Profile')),
                ('kendra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anandakendra.AnandaKendra')),
            ],
        ),
    ]
