# Generated by Django 2.2 on 2020-06-23 15:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bandhuapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('activity_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Cultural', 'Cultural'), ('Sports', 'Sports'), ('Debate', 'Debate')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Activity Categories',
            },
        ),
        migrations.CreateModel(
            name='AnandaKendra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('address', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='anandkendra/kendras')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bandhuapp.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('guardian_name', models.CharField(max_length=50)),
                ('school_class', models.CharField(max_length=15)),
                ('contact_no', models.CharField(max_length=13, verbose_name='Contact Number')),
                ('address', models.CharField(max_length=250)),
                ('kendra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anandakendra.AnandaKendra')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='anandkendra/activities')),
                ('approved', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anandakendra.Activity')),
                ('kendra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anandakendra.AnandaKendra')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anandakendra.ActivityCategory'),
        ),
        migrations.AddField(
            model_name='activity',
            name='kendra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anandakendra.AnandaKendra'),
        ),
        migrations.CreateModel(
            name='Acharya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acharya_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandhuapp.Profile')),
                ('kendra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anandakendra.AnandaKendra')),
            ],
        ),
    ]
